title: "Aktion Watch"
email: aktion.watch@gmail.com
timezone: UTC
baseurl: "/aktionwatch.github.io"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Eirini Chatzara
paginate: 30
disqus: 'demowebsite'
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
languages: ["en"]
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
default_lang: "en"
exclude_from_localization: ["javascript", "css", "images"]
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  eir:
    name: Eirini Chatzara
    display_name: Eirini
    avatar: 'assets/images/Eirini.png'
    email: eirini.chatzara@gmail.com
    web: https://www.linkedin.com/in/echatzara/
    description: "Climate Change Communication researcher | STEM Education specialist | Applied physicist"

# Social
social:
  instagram: https://www.instagram.com/bootstrapstarter/
  facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
  twitter: https://twitter.com/bstartercom

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
